// The two state-space puzzles: tuning resonance dials and shoving gravity cores.
//
// Both are generated backwards from a solved state, which is the cheapest way to
// guarantee solvability without writing a solver.

import type { Rng } from '../rng'
import { DIRS, idx, xy } from './types'
import type { GravityCoresState, PuzzleMove, ResonanceState } from './types'

// ================================================================ resonance
//
// Lights Out with three states. Tapping a dial advances it and its four
// orthogonal neighbours. Generated by tapping a solved board at random, so it
// can always be untapped.

function tapAt(values: number[], w: number, h: number, index: number, modulus: number): void {
  const { x, y } = xy(w, index)
  const bump = (i: number) => {
    values[i] = ((values[i] ?? 0) + 1) % modulus
  }
  bump(index)
  for (const d of DIRS) {
    const nx = x + d.dx
    const ny = y + d.dy
    if (nx < 0 || ny < 0 || nx >= w || ny >= h) continue
    bump(idx(w, nx, ny))
  }
}

export function generateResonance(rng: Rng, difficulty: number): ResonanceState {
  const w = difficulty >= 3 ? 5 : 4
  const h = difficulty >= 2 ? 4 : 3
  const modulus = 3
  const values = Array.from({ length: w * h }, () => 0)

  const scrambles = 3 + difficulty * 2
  for (let i = 0; i < scrambles; i++) {
    tapAt(values, w, h, rng.int(w * h), modulus)
  }

  // If the scramble happened to cancel out, nudge it once more.
  if (values.every((v) => v === 0)) tapAt(values, w, h, rng.int(w * h), modulus)

  return { w, h, values, modulus, taps: 0 }
}

export function resonanceMove(s: ResonanceState, move: PuzzleMove): ResonanceState {
  if (move.k !== 'resonanceTap') return s
  if (move.index < 0 || move.index >= s.values.length) return s
  const values = [...s.values]
  tapAt(values, s.w, s.h, move.index, s.modulus)
  return { ...s, values, taps: s.taps + 1 }
}

export function resonanceStatus(s: ResonanceState) {
  return s.values.every((v) => v === 0) ? ('solved' as const) : ('open' as const)
}

// ============================================================ gravity cores
//
// Sokoban with ancient cores. Generated by running the puzzle backwards from a
// solved board — every scrambled position therefore has a solution, and we never
// need to search for one.

function step(w: number, h: number, index: number, dir: number): number | null {
  const { x, y } = xy(w, index)
  const nx = x + DIRS[dir]!.dx
  const ny = y + DIRS[dir]!.dy
  if (nx < 0 || ny < 0 || nx >= w || ny >= h) return null
  return idx(w, nx, ny)
}

export function generateGravityCores(rng: Rng, difficulty: number): GravityCoresState {
  const w = 6
  const h = 6
  const cells = w * h
  const coreCount = difficulty >= 3 ? 3 : 2

  const walls = Array.from({ length: cells }, () => false)
  // A ring of wall around the chamber keeps the pushes readable.
  for (let x = 0; x < w; x++) {
    walls[idx(w, x, 0)] = true
    walls[idx(w, x, h - 1)] = true
  }
  for (let y = 0; y < h; y++) {
    walls[idx(w, 0, y)] = true
    walls[idx(w, w - 1, y)] = true
  }
  // A couple of interior pillars, never on the middle band so the room stays open.
  const interior = Array.from({ length: cells }, (_, i) => i).filter((i) => {
    const p = xy(w, i)
    return p.x > 0 && p.y > 0 && p.x < w - 1 && p.y < h - 1
  })
  for (const i of rng.shuffle(interior).slice(0, difficulty >= 2 ? 2 : 1)) {
    walls[i] = true
  }

  const open = interior.filter((i) => !walls[i])
  const goals = rng.shuffle(open).slice(0, coreCount)

  // Walk the puzzle backwards from the solved board. A reverse step is either a
  // plain hero walk or a PULL: the hero retreats and drags the core it faces.
  // Every position reachable this way therefore has a forward solution — which
  // is exactly why we never push anything forward during generation. An earlier
  // version nudged a core forward when the scramble came out solved, and that
  // could shove it into a corner nothing could ever recover from.
  const reverseSteps = 12 + difficulty * 8

  let cores: number[] = []
  let hero = open[0]!

  for (let attempt = 0; attempt < 24; attempt++) {
    cores = [...goals]
    hero = rng.pick(open.filter((i) => !cores.includes(i))) ?? open[0]!

    for (let i = 0; i < reverseSteps; i++) {
      let moved = false
      for (const dir of rng.shuffle([0, 1, 2, 3])) {
        const back = step(w, h, hero, (dir + 2) % 4)
        if (back === null || walls[back] || cores.includes(back)) continue

        const ahead = step(w, h, hero, dir)
        const canPull = ahead !== null && cores.includes(ahead)

        if (canPull && rng.next() < 0.7) {
          cores = cores.map((c) => (c === ahead ? hero : c))
          hero = back
          moved = true
          break
        }
        if (!canPull) {
          hero = back
          moved = true
          break
        }
      }
      if (!moved) break
    }

    // Only accept a scramble that actually left work to do.
    if (cores.some((c) => !goals.includes(c))) break
  }

  return { w, h, walls, cores, goals, hero, moves: 0, history: [] }
}

function snapshot(s: GravityCoresState): string {
  return JSON.stringify({ cores: s.cores, hero: s.hero })
}

export function gravityCoresMove(s: GravityCoresState, move: PuzzleMove): GravityCoresState {
  if (move.k === 'coreUndo') {
    const history = [...s.history]
    const last = history.pop()
    if (!last) return s
    const parsed = JSON.parse(last) as { cores: number[]; hero: number }
    return { ...s, cores: parsed.cores, hero: parsed.hero, history, moves: s.moves + 1 }
  }

  if (move.k !== 'coreStep') return s
  const dir = ((move.dir % 4) + 4) % 4
  const ahead = step(s.w, s.h, s.hero, dir)
  if (ahead === null || s.walls[ahead]) return s

  const before = snapshot(s)

  // Empty tile: just walk.
  if (!s.cores.includes(ahead)) {
    return {
      ...s,
      hero: ahead,
      moves: s.moves + 1,
      history: [...s.history, before].slice(-60),
    }
  }

  // A core: push it, if there is room behind.
  const beyond = step(s.w, s.h, ahead, dir)
  if (beyond === null || s.walls[beyond] || s.cores.includes(beyond)) return s
  return {
    ...s,
    hero: ahead,
    cores: s.cores.map((c) => (c === ahead ? beyond : c)),
    moves: s.moves + 1,
    history: [...s.history, before].slice(-60),
  }
}

export function gravityCoresStatus(s: GravityCoresState) {
  return s.cores.every((c) => s.goals.includes(c)) ? ('solved' as const) : ('open' as const)
}
