// The three spatial puzzles: routing power, bending light, fitting star charts.
//
// All three are generated by building a valid solution first and then scrambling
// it. Scrambling only ever changes rotations or placement, never the underlying
// structure, so a solution is guaranteed to exist — no solver needed.

import type { Rng } from '../rng'
import { DIRS, idx, xy } from './types'
import type { PowerRoutingState, PuzzleMove, RefractionState, StarChartState } from './types'

// ============================================================ power routing
//
// Rotate the conduits until the reactor feeds every terminal. Two tiles are
// connected only when BOTH point at each other — that is what makes rotating one
// tile matter to its neighbour.

/** Rotate a connection mask one quarter turn clockwise. */
export function rotateMask(mask: number, times = 1): number {
  let m = mask & 0xf
  for (let i = 0; i < ((times % 4) + 4) % 4; i++) m = ((m << 1) | (m >> 3)) & 0xf
  return m
}

function neighbourIn(w: number, h: number, index: number, dir: number): number | null {
  const { x, y } = xy(w, index)
  const nx = x + DIRS[dir]!.dx
  const ny = y + DIRS[dir]!.dy
  if (nx < 0 || ny < 0 || nx >= w || ny >= h) return null
  return idx(w, nx, ny)
}

/** Which terminals does the reactor currently reach? */
export function poweredTiles(s: PowerRoutingState): Set<number> {
  const seen = new Set<number>([s.source])
  const stack = [s.source]
  while (stack.length > 0) {
    const at = stack.pop()!
    for (let dir = 0; dir < 4; dir++) {
      if (!(s.masks[at]! & (1 << dir))) continue
      const next = neighbourIn(s.w, s.h, at, dir)
      if (next === null || s.empty[next] || seen.has(next)) continue
      // The neighbour has to point back, otherwise the conduits do not meet.
      if (!(s.masks[next]! & (1 << ((dir + 2) % 4)))) continue
      seen.add(next)
      stack.push(next)
    }
  }
  return seen
}

export function generatePowerRouting(rng: Rng, difficulty: number): PowerRoutingState {
  const w = difficulty >= 3 ? 5 : 4
  const h = difficulty >= 2 ? 4 : 3
  const cells = w * h

  const masks = Array.from({ length: cells }, () => 0)
  const inTree = Array.from({ length: cells }, () => false)
  const degree = Array.from({ length: cells }, () => 0)

  const source = idx(w, 0, h - 1)
  inTree[source] = true
  const wanted = Math.max(cells - 3, Math.floor(cells * 0.75))
  let size = 1

  // Randomised growth: pick a tile already in the tree, extend it outwards.
  let guard = cells * 40
  while (size < wanted && guard-- > 0) {
    const from = rng.pick(Array.from({ length: cells }, (_, i) => i).filter((i) => inTree[i]))
    if (from === undefined) break
    const dir = rng.int(4)
    const to = neighbourIn(w, h, from, dir)
    if (to === null || inTree[to]) continue
    masks[from]! |= 1 << dir
    masks[to]! |= 1 << ((dir + 2) % 4)
    degree[from] += 1
    degree[to] += 1
    inTree[to] = true
    size += 1
  }

  // Terminals: leaves of the tree, as far from the reactor as possible.
  const leaves = Array.from({ length: cells }, (_, i) => i)
    .filter((i) => inTree[i] && i !== source && degree[i] === 1)
    .sort((a, b) => {
      const pa = xy(w, a)
      const pb = xy(w, b)
      const ps = xy(w, source)
      const da = Math.abs(pa.x - ps.x) + Math.abs(pa.y - ps.y)
      const db = Math.abs(pb.x - ps.x) + Math.abs(pb.y - ps.y)
      return db - da
    })
  const targets = leaves.slice(0, Math.min(leaves.length, difficulty >= 2 ? 3 : 2))

  const state: PowerRoutingState = {
    w,
    h,
    masks,
    empty: inTree.map((t) => !t),
    source,
    targets: targets.length > 0 ? targets : leaves.slice(0, 1),
    rotations: 0,
    solvedMasks: [...masks],
  }

  // Scramble. Rotating a tile can never make the puzzle unsolvable, only harder.
  for (let i = 0; i < cells; i++) {
    if (state.empty[i]) continue
    state.masks[i] = rotateMask(state.masks[i]!, rng.int(4))
  }

  // Guarantee it does not start already solved.
  if (powerRoutingStatus(state) === 'solved') {
    const spinnable = Array.from({ length: cells }, (_, i) => i).find(
      (i) => !state.empty[i] && rotateMask(state.masks[i]!, 1) !== state.masks[i],
    )
    if (spinnable !== undefined) state.masks[spinnable] = rotateMask(state.masks[spinnable]!, 1)
  }

  return state
}

export function powerRoutingMove(s: PowerRoutingState, move: PuzzleMove): PowerRoutingState {
  if (move.k !== 'routeRotate') return s
  if (move.index < 0 || move.index >= s.masks.length || s.empty[move.index]) return s
  const masks = [...s.masks]
  masks[move.index] = rotateMask(masks[move.index]!, 1)
  return { ...s, masks, rotations: s.rotations + 1 }
}

export function powerRoutingStatus(s: PowerRoutingState) {
  const powered = poweredTiles(s)
  return s.targets.every((t) => powered.has(t)) ? ('solved' as const) : ('open' as const)
}

// ================================================================ refraction
//
// Steer the rune-light onto every focus. Mirrors are '/' or '\\'; you flip them
// by clicking. Beautiful, and completely language free.

/** Reflect a direction off a mirror. 1 = '/', 2 = '\\'. */
export function reflect(dir: number, mirror: number): number {
  if (mirror === 1) return dir === 0 ? 1 : dir === 1 ? 0 : dir === 2 ? 3 : 2
  if (mirror === 2) return dir === 0 ? 3 : dir === 3 ? 0 : dir === 1 ? 2 : 1
  return dir
}

/** Trace the beam. Returns every tile it passes through, in order. */
export function traceBeam(s: RefractionState): number[] {
  const path: number[] = []
  const blockers = new Set(s.blockers)
  let at = s.emitter
  let dir = s.emitterDir
  let guard = s.w * s.h * 4

  while (guard-- > 0) {
    const next = neighbourIn(s.w, s.h, at, dir)
    if (next === null) break
    if (blockers.has(next)) break
    path.push(next)
    const mirror = s.mirrors[next] ?? 0
    if (mirror !== 0) dir = reflect(dir, mirror)
    at = next
  }

  return path
}

export function generateRefraction(rng: Rng, difficulty: number): RefractionState {
  const w = difficulty >= 3 ? 7 : 6
  const h = difficulty >= 2 ? 6 : 5
  const cells = w * h
  const mirrorCount = difficulty >= 3 ? 5 : difficulty >= 2 ? 4 : 3

  // Several attempts, because a path has to satisfy two things at once: it must
  // bend at least once, and the foci must sit AFTER the first bend. Otherwise
  // flipping mirrors could never fail to solve it, and the puzzle would open
  // already finished.
  for (let attempt = 0; attempt < 30; attempt++) {
    const mirrors = Array.from({ length: cells }, () => 0)
    /** Tiles the beam visits, in order, with the index of the first mirror. */
    const visited: number[] = []
    let firstMirrorAt = -1

    const emitterY = rng.between(1, h - 2)
    const emitter = idx(w, 0, emitterY)
    let at = emitter
    let dir = 1
    let placed = 0
    let guard = cells * 3

    while (placed < mirrorCount && guard-- > 0) {
      const next = neighbourIn(w, h, at, dir)
      if (next === null) {
        // The beam is about to leave the grid, so it has to turn where it stands.
        if (at === emitter) break
        const first = rng.next() < 0.5 ? 1 : 2
        const second = first === 1 ? 2 : 1
        const pick = neighbourIn(w, h, at, reflect(dir, first)) !== null ? first : second
        if (neighbourIn(w, h, at, reflect(dir, pick)) === null) break
        mirrors[at] = pick
        if (firstMirrorAt < 0) firstMirrorAt = visited.indexOf(at)
        dir = reflect(dir, pick)
        placed += 1
        continue
      }

      at = next
      visited.push(at)

      // Turn now and then, so the path actually snakes.
      if (mirrors[at] === 0 && rng.next() < 0.45) {
        const turn = rng.next() < 0.5 ? 1 : 2
        const newDir = reflect(dir, turn)
        if (neighbourIn(w, h, at, newDir) !== null) {
          mirrors[at] = turn
          if (firstMirrorAt < 0) firstMirrorAt = visited.length - 1
          dir = newDir
          placed += 1
        }
      }
    }

    if (firstMirrorAt < 0) continue

    // Foci only downstream of the first mirror, and never on a mirror tile.
    const wanted = difficulty >= 2 ? 3 : 2
    const downstream = visited
      .slice(firstMirrorAt + 1)
      .filter((c) => mirrors[c] === 0 && c !== emitter)
    const targets: number[] = []
    for (const c of rng.shuffle(downstream)) {
      if (targets.length >= wanted) break
      if (!targets.includes(c)) targets.push(c)
    }
    if (targets.length === 0) continue

    // Blockers well away from the intended path, purely to narrow the options.
    const onPath = new Set([...visited, emitter])
    const blockers = rng
      .shuffle(Array.from({ length: cells }, (_, i) => i).filter((i) => !onPath.has(i)))
      .slice(0, difficulty >= 2 ? 4 : 2)

    const base: RefractionState = {
      w,
      h,
      emitter,
      emitterDir: 1,
      mirrors,
      blockers,
      targets,
      rotations: 0,
    }

    // Enumerate every orientation combination and start from one that is NOT
    // already solved. With at most five mirrors this is 32 cases — cheaper and
    // far more reliable than flipping one at random and hoping.
    const mirrorIndexes = mirrors.map((m, i) => (m !== 0 ? i : -1)).filter((i) => i >= 0)
    const open: number[][] = []
    for (let combo = 0; combo < 1 << mirrorIndexes.length; combo++) {
      const candidate = [...mirrors]
      mirrorIndexes.forEach((index, bit) => {
        candidate[index] = combo & (1 << bit) ? 2 : 1
      })
      if (refractionStatus({ ...base, mirrors: candidate }) === 'open') open.push(candidate)
    }
    const scrambled = rng.pick(open)
    if (!scrambled) continue

    return { ...base, mirrors: scrambled }
  }

  // Fallback: a hand-built board, so a bad run of luck can never hand back a
  // broken puzzle. Beam east, one mirror turning it south, one focus below.
  const emitter = idx(w, 0, 1)
  const mirrorAt = idx(w, 3, 1)
  const mirrors = Array.from({ length: cells }, () => 0)
  mirrors[mirrorAt] = 1
  return {
    w,
    h,
    emitter,
    emitterDir: 1,
    mirrors,
    blockers: [],
    targets: [idx(w, 3, 3)],
    rotations: 0,
  }
}

export function refractionMove(s: RefractionState, move: PuzzleMove): RefractionState {
  if (move.k !== 'refractRotate') return s
  const current = s.mirrors[move.index]
  if (current === undefined || current === 0) return s
  const mirrors = [...s.mirrors]
  mirrors[move.index] = current === 1 ? 2 : 1
  return { ...s, mirrors, rotations: s.rotations + 1 }
}

export function refractionStatus(s: RefractionState) {
  const hit = new Set(traceBeam(s))
  return s.targets.every((t) => hit.has(t)) ? ('solved' as const) : ('open' as const)
}

// ================================================================ star chart
//
// Fit the chart fragments together so the star lines run on across the seams.
// Pure edge matching: rotate and place until every seam agrees.

/** Which edge code sits on the given side, given the fragment's rotation. */
export function edgeAt(edges: readonly number[], rotation: number, dir: number): number {
  return edges[(((dir - rotation) % 4) + 4) % 4]!
}

export function generateStarChart(rng: Rng, difficulty: number): StarChartState {
  const size = difficulty >= 2 ? 3 : 2
  const cells = size * size
  const codes = 4

  // Internal seams get a shared code; the outer border is left free.
  const vertical: number[][] = Array.from({ length: size }, () =>
    Array.from({ length: size - 1 }, () => 1 + rng.int(codes)),
  )
  const horizontal: number[][] = Array.from({ length: size - 1 }, () =>
    Array.from({ length: size }, () => 1 + rng.int(codes)),
  )

  const solution: number[][] = []
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      solution.push([
        y > 0 ? horizontal[y - 1]![x]! : 0,
        x < size - 1 ? vertical[y]![x]! : 0,
        y < size - 1 ? horizontal[y]![x]! : 0,
        x > 0 ? vertical[y]![x - 1]! : 0,
      ])
    }
  }

  // Hand the fragments over shuffled and randomly turned.
  const order = rng.shuffle(Array.from({ length: cells }, (_, i) => i))
  const fragments = order.map((i) => solution[i]!)

  return {
    size,
    fragments,
    placement: Array.from({ length: cells }, () => null),
    rotation: fragments.map(() => rng.int(4)),
  }
}

export function starChartMove(s: StarChartState, move: PuzzleMove): StarChartState {
  if (move.k === 'chartPlace') {
    if (move.cell < 0 || move.cell >= s.placement.length) return s
    if (move.fragment < 0 || move.fragment >= s.fragments.length) return s
    const placement = [...s.placement]
    // If this fragment sits somewhere already, lift it first.
    const from = placement.indexOf(move.fragment)
    if (from >= 0) placement[from] = null
    // Whatever was in the target cell goes back to the tray.
    placement[move.cell] = move.fragment
    return { ...s, placement }
  }
  if (move.k === 'chartLift') {
    const placement = [...s.placement]
    placement[move.cell] = null
    return { ...s, placement }
  }
  if (move.k === 'chartRotate') {
    const rotation = [...s.rotation]
    rotation[move.fragment] = ((rotation[move.fragment] ?? 0) + 1) % 4
    return { ...s, rotation }
  }
  return s
}

export function starChartStatus(s: StarChartState) {
  if (s.placement.some((p) => p === null)) return 'open' as const
  const size = s.size
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const here = s.placement[y * size + x]!
      if (x < size - 1) {
        const right = s.placement[y * size + x + 1]!
        if (
          edgeAt(s.fragments[here]!, s.rotation[here]!, 1) !==
          edgeAt(s.fragments[right]!, s.rotation[right]!, 3)
        ) {
          return 'open' as const
        }
      }
      if (y < size - 1) {
        const below = s.placement[(y + 1) * size + x]!
        if (
          edgeAt(s.fragments[here]!, s.rotation[here]!, 2) !==
          edgeAt(s.fragments[below]!, s.rotation[below]!, 0)
        ) {
          return 'open' as const
        }
      }
    }
  }
  return 'solved' as const
}
